"""
Validation C1: is an explicit lapse model identifiable at the proposed
allocation, with and without catch trials?

Generative model: the Task 04 linear-weight observer (ordinal_model.
simulate_responses). Catch trials are generated by the same latent model at
(d_on, d_off) = (+/-8, +/-8), i.e. extreme congruent asynchronies.

Fitted models on the same datasets:
  L0  standard model, 20 main trials                     (Task 04 baseline)
  L1  lapse model, 20 main trials                        (Task 04 lapse model)
  L2  lapse model, 20 main + K catch trials jointly      (catch trials in likelihood)
  L3  two-step: lambda_hat = 1.5 x catch error rate (clipped to [0, 0.5]),
      then lapse model on 20 main trials with lambda fixed at lambda_hat.
      Wald SE does not include uncertainty in lambda_hat (stated limitation).

Checkpointed: one JSON line per (scenario, K, rep); reruns skip existing keys.

Usage: python3 lapse_catch.py --reps 100 --workers 2 --out ../results/validationC/lapse_catch.jsonl
"""
import argparse
import hashlib
import json
import os
import time
from multiprocessing import Pool

import numpy as np
from scipy.optimize import minimize
from scipy.special import logit

import stimulus as st
import ordinal_model as om

N = 12
NS = "task05-C1-v1"
SCENARIOS = {
    "S01 onset moderate (lapse 0.02)":  dict(w_on=0.7, w_off=0.0, lapse=0.02),
    "S12 onset moderate (lapse 0.15)":  dict(w_on=0.7, w_off=0.0, lapse=0.15),
    "S04 midpoint moderate (lapse 0.15)": dict(w_on=0.35, w_off=0.35, lapse=0.15),
    "S10 guessing (lapse 0.02)":        dict(w_on=0.0, w_off=0.0, lapse=0.02),
}
KS = (4, 8)


def seed(*p):
    return int(hashlib.sha256("|".join([NS, *map(str, p)]).encode()).hexdigest()[:16], 16)


def fit_fixed_lapse(don, doff, y, lam):
    lam = float(np.clip(lam, 1e-4, 0.5))
    lz = logit(lam)
    f = lambda p: om.negloglik(np.append(p, lz), don, doff, y, True)
    b = om._bounds(False)
    r = minimize(f, np.array([-1.0, np.log(2.0), 0.0, 0.0, np.log(0.5)]), method="L-BFGS-B",
                 bounds=b, options={"maxiter": 1000, "ftol": 1e-12, "gtol": 1e-7})
    x = r.x
    free = [i for i in range(5) if not (i == 4 and abs(x[4] - b[4][0]) < 1e-3)]
    def ff(z):
        p = x.copy(); p[free] = z
        return f(p)
    try:
        H = om.num_hessian(ff, x[free]); cov = np.linalg.inv(H)
        iw = [free.index(2), free.index(3)]
        se = np.sqrt(np.clip(np.diag(cov)[iw], 0, None))
        pd = bool(np.all(np.linalg.eigvalsh(H) > 0))
    except np.linalg.LinAlgError:
        se = np.array([np.nan, np.nan]); pd = False
    at_w = any(abs(x[i] - b[i][0]) < 1e-3 or abs(x[i] - b[i][1]) < 1e-3 for i in (2, 3))
    return {"w_on": float(x[2]), "w_off": float(x[3]), "se_w_on": float(se[0]), "se_w_off": float(se[1]),
            "stable": bool(r.success and pd and not at_w and np.all(np.isfinite(se)))}


def one(job):
    scen, K, rep = job
    p = SCENARIOS[scen]
    rng = np.random.default_rng(seed(scen, K, rep))
    tm = st.order_templates(2, 4)
    d_on_m = np.array([t.d_on for t in tm]); d_off_m = np.array([t.d_off for t in tm])
    signs = np.array([+1, -1] * (K // 2), dtype=float)
    d_on_c = 8.0 * signs; d_off_c = 8.0 * signs
    don = np.tile(np.concatenate([d_on_m, d_on_c]), (N, 1))
    doff = np.tile(np.concatenate([d_off_m, d_off_c]), (N, 1))
    y = om.simulate_responses(rng, don, doff, p["w_on"], p["w_off"], tau=1.0, bias_sd=0.5, lapse=p["lapse"])
    m = slice(0, 20); c = slice(20, 20 + K)
    out = {"key": f"{scen}|K{K}|rep{rep}", "scenario": scen, "K": K, "rep": rep, "seed": str(seed(scen, K, rep)),
           "true": p}
    t0 = time.perf_counter()
    f0 = om.fit(don[:, m], doff[:, m], y[:, m])
    f1 = om.fit(don[:, m], doff[:, m], y[:, m], lapse=True)
    f2 = om.fit(don, doff, y, lapse=True)
    correct_c = (y[:, c] == np.where(d_on_c > 0, 2, 0)[None, :])
    err = 1.0 - correct_c.mean()
    lam_hat = float(np.clip(1.5 * err, 0.0, 0.5))
    f3 = fit_fixed_lapse(don[:, m], doff[:, m], y[:, m], lam_hat)
    for name, f in (("L0", f0), ("L1", f1), ("L2", f2), ("L3", f3)):
        out[name] = {k: (float(f[k]) if not isinstance(f[k], bool) else f[k])
                     for k in ("w_on", "w_off", "se_w_on", "se_w_off", "stable")}
        if name in ("L1", "L2"):
            out[name]["lapse_hat"] = float(f["lapse"])
            out[name]["lapse_at_boundary"] = bool(f["lapse_at_boundary"])
    out["L3"]["lapse_hat"] = lam_hat
    out["catch_error_rate"] = float(err)
    out["catch_errors_per_participant"] = (K - correct_c.sum(1)).tolist()
    out["seconds"] = round(time.perf_counter() - t0, 3)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reps", type=int, default=100)
    ap.add_argument("--workers", type=int, default=2)
    ap.add_argument("--out", required=True)
    ap.add_argument("--scenarios", nargs="+", default=list(SCENARIOS))
    args = ap.parse_args()
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    done = set()
    if os.path.exists(args.out):
        for l in open(args.out):
            done.add(json.loads(l)["key"])
    jobs = [(s, K, r) for s in args.scenarios for K in KS for r in range(args.reps)
            if f"{s}|K{K}|rep{r}" not in done]
    print(f"pending {len(jobs)}, already done {len(done)}", flush=True)
    t0 = time.time()
    with Pool(args.workers) as p, open(args.out, "a") as f:
        for i, row in enumerate(p.imap(one, jobs, chunksize=5)):
            f.write(json.dumps(row) + "\n"); f.flush()
            if (i + 1) % 100 == 0:
                el = time.time() - t0
                print(json.dumps({"done": i + 1, "of": len(jobs), "elapsed_s": round(el, 1),
                                  "eta_s": round(el / (i + 1) * (len(jobs) - i - 1), 1)}), flush=True)
    print("finished", round(time.time() - t0, 1), "s")


if __name__ == "__main__":
    main()
